classDiagram
    OnePieceCharacter  "1" --> "1" Origin: Born in 
    OnePieceCharacter "1" --> "1" Crew: Part of
    OnePieceCharacter "1" --> "1" PirateFleet: Serves in
    OnePieceCharacter "1" --> "0..*" DevilFruit: Has eaten 
    DevilFruit "1" --> "1" DevilFruitType : Is Type of
    
    class OnePieceCharacter{
      +String Name
      +String BloodType
      +String Occupation
      +String NickName
      +bool IsAlive
      +bool HasDevilFruit
      +bool IsPartOfFleet
      +int Bounty
      +int Age
      +int Height
      +Date BirthDay
      +eat(DevilFruit)
    }  

    class DevilFruit{
      +String Name
      +String Meaning           
    }  

    class DevilFruitType {
    <<enumeration>>
      Paramecia
      Zoan
      Logia
    }
    
    class Origin{
      +String Name      
      +bool isKingdom           
    }
        
    class Crew {
      +String Name
      +String OceanOfOrigin
      +String Captain
      +String MainShip
      +int TotalBounty
    }

    class PirateFleet {
    +String Name
    +String Captain
    +int TotalPeople
    +int TotalBounty
    }

    
     