---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: api
  labels:
    app: api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: api
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: api:latest
        imagePullPolicy: Always
        name: api
        resources:
          limits:
            memory: 2048Mi
            cpu: 500m
        env:
           - name: "URL"
             value: "http://api:5000/v1/whoami"
      restartPolicy: Always
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
        - api
      from:
        kind: ImageStreamTag
        name: api:latest
    type: ImageChange